source = blink.c
object = blink.o
hexfile = blink.hex
CC=avr-gcc
OBJCC= avr-objcopy
LIBS=
board=atmega328p
port=/dev/ttyUSB0
baud=57600
DEFS= 
FREQ= 16000000UL
executable= blink.elf

all: compile program clean

.PHONY: compile

compile:
	$(CC) -Os -DF_CPU=$(FREQ) -mmcu=$(board) $(DEFS) -c -o $(object) $(source) $(LIBS)
	$(CC) -mmcu=$(board) $(object) -o $(executable)
	$(OBJCC) -O ihex -R .eeprom $(executable) $(hexfile)

.PHONY: program

program: 
	sudo avrdude -v -p $(board) -c arduino -P $(port) -b $(baud) -D -U flash:w:$(hexfile):i

.PHONY: clean

clean: 
	rm -f $(object) $(executable) $(hexfile)
