source = blink.c
CC=avr-gcc
OBJCC= avr-objcopy
LIBS=
board=atmega328p
port=/dev/ttyUSB0
baud=57600
DEFS= 
FREQ= 16000000UL
executable= blink.elf

all: compile program clean

.PHONY: compile

compile:
	$(CC) -Os -DF_CPU=$(FREQ) -mmcu=$(board) $(DEFS) -c -o $(source:%.c=%.o) $(source) $(LIBS)
	$(CC) -mmcu=$(board) $(source:%.c=%.o) -o $(executable)
	$(OBJCC) -O ihex -R .eeprom $(executable) $(source:%.c=%.hex)

.PHONY: program

program: 
	sudo avrdude -v -p $(board) -c arduino -P $(port) -b $(baud) -D -U flash:w:$(source:%.c=%.hex):i

.PHONY: clean

clean: 
	rm -f $(source:%.c=%.o) $(executable) $(source:%.c=%.hex)
