all: compile program clean

.PHONY: compile

compile:
	avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o blink.o blink.c
	avr-gcc -mmcu=atmega328p blink.o -o blink
	avr-objcopy -O ihex -R .eeprom blink blink.hex

.PHONY: program

program: 
	sudo avrdude -v -p atmega328p -c arduino -P /dev/ttyUSB0 -b 57600 -D -U flash:w:blink.hex:i

.PHONY: clean

clean: 
	rm -f blink.o blink blink.hex
